// <auto-generated />
// ReSharper disable All
using System;
using Android.App;
using Android.Support.V7.Widget;
using Android.Views;
using Android.Widget;
using JetBrains.Annotations;

namespace VacationsTracker.Droid.Views
{
    /*
    "activity_login" layout file doesn't contain any view with "android:id" attribute specified. There is no sense in view holder generation.
    public partial class LoginActivityViewHolder
    {
    }
    */

}
// ReSharper restore All
