// <auto-generated />
// ReSharper disable All
using System;
using Android.App;
using Android.Support.V7.Widget;
using Android.Views;
using Android.Widget;

namespace VacationsTracker.Droid.Views
{
    public partial class LoginActivityViewHolder
    {
         private readonly Activity activity;

         private TextView headerTextView;
         private Button loginButton;

        public LoginActivityViewHolder( Activity activity)
        {
            if (activity == null) throw new ArgumentNullException(nameof(activity));

            this.activity = activity;
        }

        
        public TextView HeaderTextView =>
            headerTextView ?? (headerTextView = activity.FindViewById<TextView>(Resource.Id.header_text_view));

        
        public Button LoginButton =>
            loginButton ?? (loginButton = activity.FindViewById<Button>(Resource.Id.login_button));
    }

}
// ReSharper restore All
